### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by MichalGrzegorzak** [episerver/EPiServer.Warmup#1]
The module is called, but actually the condition UserAgent set to "SiteWarmup", is never true.
Does it need some specific setup in Azure?

**Comment by ksjoberg** [comment]
We're looking into this. While that's ongoing, the user agent "AlwaysOn" seem to work alright.

**Comment by MichalGrzegorzak** [comment]
Hi, 
still no luck.
I have added logging there and I`m capturing all of unique user agents, and have only those:

Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; GTMProbe 1.0), 
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36, 
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.4 (KHTML, like Gecko) Chrome/98 Safari/537.4 (StatusCake), 
Mozilla/5.0 (iPad; CPU OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1, 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.3600 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36 RuxitSynthetic/1.0, 
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 (StatusCake), 
Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html), 
AddThis.com (http://support.addthis.com/), 
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36, 
Mozilla/5.0 (Windows NT 5.1; rv:31.0) Gecko/20100101 Firefox/31.0, 
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.75 Safari/537.36 Google Favicon, 
Mozilla/5.0 (Windows NT 6.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36, 
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1, 
Mozilla/5.0 (Windows NT 5.1) AppleWebKit/534.27+ (KHTML, like Gecko) Version/5.0.4 Safari/533.20.27, 
Mozilla/5.0 (compatible; MJ12bot/v1.4.5; http://www.majestic12.co.uk/bot.php?+), 
expo9, 
Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13E238 Safari/601.1, 
Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp), 
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36, 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36

**Comment by ksjoberg** [comment]
This surprises me, because I have seen “AlwaysOn” as a  user agent in the log files. It could be a setting on the web app – you running on Azure natively or on a DXC setup?

**Comment by MichalGrzegorzak** [comment]
I`m running on DXC. And I can confirm that AlwaysOn setting is enabled on webapp.

**Comment by MichalGrzegorzak** [comment]
It started to work, but AlwaysOn was enabled, so I don`t quite now what was the problem.
