### ISSUE TITLE
Question - how it can warmup multi-tenant Episerver site

### ISSUE THREAD

**Issue by MichalGrzegorzak** [episerver/EPiServer.Warmup#2]
If I want to warmup 2 homepages on 2 different sites:
- example.com/
- different-example.com/

So in the end both calls will look the same:
-> 127.0.0.1/
-> 127.0.0.1/

I think there is no way that Epi will warmup both sites, or am I wrong?

**Comment by ksjoberg** [comment]
The Host header will be passed with different values (example.com and different-example.com).

**Comment by ksjoberg** [comment]
Actually, there's a changed version that does the requests differently that I haven't pushed yet because it turns out that the Azure environment does not allow for TCP connections to localhost.

**Comment by MichalGrzegorzak** [comment]
Thanks, waiting for the new version then.

**Comment by ksjoberg** [comment]
There you have it! Thanks for exploring this. I'll check why you aren't seeing the AlwaysOn-request in your logs.
