### ISSUE TITLE
Multitenant Episerver instalation

### ISSUE THREAD

**Issue by MichalGrzegorzak** [episerver/EPiServer.Warmup#3]
Hi, 
have 2 different sites under Episerver Root tree.
Warmup module seems to be working only for the first site, for the second site it throws 404 errors only.
Any ideas why?

**Comment by ksjoberg** [comment]
I'd say it's because of you having only relative URLs in your warmup urls file. In order to route the request to the other site, an absolute url (including http:// and host name) will have to be entered.

**Comment by MichalGrzegorzak** [comment]
Thanks for answer,  no that was not the case. I had full URL with https:// all the time.
But as I`m checking the logs now, I can see that all hosts were resolved correctly - so I have no idea what happened before :/
